spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
      
uname: 
  sp: zyd
  
---
spring:
  profiles: localhost
url: http://www.aaaaa.com

---
spring:
  profiles: test
url: http://www.sina.com
